### ISSUE TITLE
Incorrect link in README

### ISSUE THREAD

**Issue by nyboer** [RyanBluth/Bandcamp-Greasy#10]
The README about installation has an incorrect link for the DownloadAlbum script. It currently links to 
https://github.com/RyanBluth/Bandcamp-Greasy/raw/master/DownloadCollection.user.js
but should link to 
https://github.com/RyanBluth/Bandcamp-Greasy/raw/master/DownloadAlbum.user.js
Once I figured this out I was able to install and use it. Nice work, thanks!

**Comment by RyanBluth** [comment]
Thanks for catching this, I've fixed it now
