### ISSUE TITLE
No downloads, only taken to first album

### ISSUE THREAD

**Issue by JLMoriart** [RyanBluth/Bandcamp-Greasy#16]
Howdy, this looks like exactly the tool I was looking for. Unfortunately, after the blue Greasy section loads all my albums and I click "Download All", I'm only taken to the first album which goes through "Preparing...", then shows "download", and then the page closes, taking me back to my collection with the blue Greasy section open. It seems to stop there. (And it seems like even that first album was not downloaded, either, unless I'm not looking for it in the right place.)

I'm on Linux 18.04 in Brave Browser, Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)

Anything I can do to troubleshoot, or log files I can provide? Thanks very much for any help!

(PS. I'd be happy to tip some Bitcoin Cash to whoever helps me get this working, at least to show that I value people's time and effort. Thanks again.)

**Comment by RyanBluth** [comment]
I just tried this out and had the same issue. The solution was to allow popups on the collection page and then reload. Once I did that it worked as expected. Let me know if that helps

**Comment by JLMoriart** [comment]
Thanks very much for the reply. I did try turning off Brave's "shields" for Bandcamp.com. Would that not do it? Even after a little googling, I can't find a specific popup setting.

**Comment by RyanBluth** [comment]
Go to Settings -> Site Settings -> Pop-ups and redirects and you will see an "Allow" section. Add https://bandcamp.com to the list and it should do the trick

**Comment by RyanBluth** [comment]
Were you able to get things working?

**Comment by jknechtel75** [comment]
yeah I did

**Comment by JLMoriart** [comment]
Sorry for the slow reply! I didn't find the "site settings" there, but I did find them by visiting the site and clicking the little lock icon to the left of the url, clicking "site settings" in that little window that pops up, and then finding "pop ups" and selecting "allow" from the drop down box.

https://support.brave.com/hc/en-us/articles/360018205431-How-do-I-change-site-permissions-

That got the downloads working. Thanks again for the help!

@GitCash 0.1 bch @RyanBluth

**Comment by realityfabric** [comment]
I had this problem in Firefox as well, and allowing popups worked like a charm. Can you add this to the instructions page?
