### ISSUE TITLE
Getting Error 429 Too Many Requests 

### ISSUE THREAD

**Issue by alexjapp** [RyanBluth/Bandcamp-Greasy#17]
Is there a way to use rate limiting to avoid this error?

**Comment by RyanBluth** [comment]
How many albums were you trying to download?

**Comment by alexjapp** [comment]
77

**Comment by RyanBluth** [comment]
I might be able to add something to solve this; probably some sort of delay after opening each album. In the meantime, I'd suggest using the download range option to download 20 or so at a time. If you take a little break between each set it should solve the problem hopefully.

**Comment by alexjapp** [comment]
Cool, thanks.

**Comment by Fewshin** [comment]
I actually fixed this last night. I'll make a PR

**Comment by dromer** [comment]
I ran into this trying to download 11 albums from my account. In FLAC.

The first 4 went through fine, but after that all tabs got this warning.

**Comment by duntwave** [comment]
same thing happening to me with FLACs. wish for any type of fix honestly I just like having downloads going while I'm asleep. works fine with mp3s typically.

**Comment by duntwave** [comment]
I think maybe an album queue timer or delay or whatever would help instead of just opening everything at the same time

**Comment by RyanBluth** [comment]
I'll try to take a look at this soon. I think adding a delay between downloads is the only solution that'll work probably

**Comment by RyanBluth** [comment]
I've added an option to throttle downloads. There are global variables at the top of the script that you can change or you can enable it through the UI

**Comment by duntwave** [comment]
everything seems to be working much more smoothly now! thanks a million. I'll put this on while I sleep and report back

**Comment by duntwave** [comment]
btw there should be an option to make it sequential where it'll only trigger the next download after one or however many you choose have completed. not sure how you'd do that but just a thought

**Comment by RyanBluth** [comment]
I don't think that's possible since the download process is controlled by the browser. I am also pretty sure that the frequency of requests is measured by the start of each request, not the completion
