### ISSUE TITLE
Only the first 219 albums were shown

### ISSUE THREAD

**Issue by Joey-2001** [RyanBluth/Bandcamp-Greasy#19]
Hi, just try these scripts with Greasemonkey and they are great for downloading huge discographies.
But I just buy a discography with 271 albums and when I try to download, only the first 219 albums are shown in my collection.
I have 858 albums there.
Is it possible to increase the number?

**Comment by RyanBluth** [comment]
You will need to increase albumLoadDuration in downloadUserCollection.js. With that many albums you may need make it more like 60000. It also seems that bandcamp is limiting the number of requests people can make so you'll have to use the range option to download things in batches. I'm not sure what the upper limit is for batch size. I'm planning to take some time to hopefully fix all of these things this weekend but that should get you started for now.

**Comment by Joey-2001** [comment]
Thanks for the info. Will try it.
