### ISSUE TITLE
Can't close the UI with right-click.

### ISSUE THREAD

**Issue by Joey-2001** [RyanBluth/Bandcamp-Greasy#21]
Hi,
I can't close the UI with a right-click since a few weeks. It only opens my right-click menu.
I use FF 83, but the issue was also in 82.
Can I change something in the scripts?
Thanks.

**Comment by RyanBluth** [comment]
Can you try again with the latest changes. It should be fixed now

**Comment by Joey-2001** [comment]
It works. Thank you very much. Your scripts helps me a lot.
Best regards.

**Comment by Joey-2001** [comment]
With the current Firefox 85.0 version the error is present again.

**Comment by RyanBluth** [comment]
Are you using the latest changes? There is now a close button in the top right corner. I need to update the readme

**Comment by Joey-2001** [comment]
Oh sorry, have the older version. With the new one everything is OK.
Thanks.
