### ISSUE TITLE
Delay on Starting Download Range with Throttle Enabled 

### ISSUE THREAD

**Issue by bigchipbag** [RyanBluth/Bandcamp-Greasy#24]
I'm using Chrome with the latest version of Tampermonkey and the scripts here. 

I set a range of downloads, set the delay to 10, and then hit "Download Range"
Initially it did nothing, but about five to ten minutes later, it started downloading the selected range with the 10 second delay between downloads. 

So the downloading is working, it just seems to front-load some sort of waiting time. 

I will peek at the script and see if I see anything, but in the mean time I wanted to post the issue.

**Comment by bigchipbag** [comment]
Otherwise, this is a great tool and I saved countless hours of point and click with it :D

**Comment by RyanBluth** [comment]
I think I see the problem. I'm using rangeStart as a basis for the throttle, which might be some large number. I think a separate counter needs to be added to the download range loop and used when calculating the throttle time.

**Comment by bigchipbag** [comment]
> I think I see the problem. I'm using rangeStart as a basis for the throttle, which might be some large number. I think a separate counter needs to be added to the download range loop and used when calculating the throttle time.

Yes - my range started at 120 in this scenario. If that's manipulated it could cause a large delay. Good catch

**Comment by RyanBluth** [comment]
This has been fixed
