### ISSUE TITLE
[Question] How do I install this?

### ISSUE THREAD

**Issue by fwyrl** [RyanBluth/Bandcamp-Greasy#3]
I've done some googling, and can't, for the life of me, figure out how to install this. Help?

**Comment by J-Vaughan** [comment]
It's a script for a browser extension called Greasemonkey on Chrome and
something different-but-similar on Firefox

**Comment by fwyrl** [comment]
I know what greasemonkey is, I just don't know how to install the script into greasemonkey.

**Comment by J-Vaughan** [comment]
I'm not sure either, tbh. Sorry

**Comment by RyanBluth** [comment]
You need to install the plugin, then go to the plugin dashboard and click the add script button to add a script

**Comment by SimmoMaz** [comment]
Saw your post on Twitter to Rob Hayler and had to give this a go

I've tried the above but if I click New User Script nothing happens.
Have also tried to click install from Github page snd get a could not install error - undefined
Using Firefox on Win10

**Comment by RyanBluth** [comment]
I will look into Firefox when I get a chance, but in the mean time you can try Chrome with tamper monkey

**Comment by SimmoMaz** [comment]
Hello Ryan and thanks for this – interestingly enough I tried Tamper Monkey in Firefox after I sent the email to you.

I was able to install the script in Tamper Monkey, I just need to try it out now.  Will let you.

Cheers

S

**Comment by starkgate** [comment]
Works perfectly for me with Firefox 70 x64 and ViolentMonkey. Thank you very much!

**Comment by fwyrl** [comment]
Working fine for me now! Sorry about any confusion!
