### ISSUE TITLE
Just scrolls to bottom of collection, then nothing happens.

### ISSUE THREAD

**Issue by chasebrown** [RyanBluth/Bandcamp-Greasy#4]
Followed the read.me word for word and I am getting the issue of opening my collection, then solely scrolling to the very bottom of my collection. Does not open any download tabs.

I tried to change the download range (maybe trying to open too many tabs at once?) but still no luck.

Any ideas?

Thank you!

**Comment by RyanBluth** [comment]
It waits for 20 seconds before it starts downloading, maybe you didn't give it enough time? You can change 20,000 at the bottom of downloadCollection.js to something like 5000 to make it faster. Let me know how that goes

**Comment by cassandra-sh** [comment]
Had the same issue, but I tried reading out the error (catch (e)) and it seemed to be unable to recognize the GM_openInTab function. I changed the line 
`
GM_openInTab(link);
`
to
`
window.open(link, '_blank');
`

**Comment by RyanBluth** [comment]
Hmm interesting, are you using chrome or Firefox?

**Comment by cassandra-sh** [comment]
Firefox, lubuntu 18.04 LTS, Firefox for ubuntu version 61.0.1 (64 bit)

**Comment by RyanBluth** [comment]
I'll try to get around to testing your solution in chrome. If it works then I can add that change, or you can open a PR if you're up to it

**Comment by con3644** [comment]
I had the same problem with Firefox 64bit on Windows 10 and cassandra-sh's fix worked for me.

**Comment by RyanBluth** [comment]
In DownloadCollection.js you can set a range of albums, so you can just do 10 at a time or something

**Comment by RyanBluth** [comment]
This should be fixed
