### ISSUE TITLE
Bulkdownload

### ISSUE THREAD

**Issue by klonamy** [RyanBluth/Bandcamp-Greasy#5]
Hello there,

first great script. It work very well for small collections!
But i have a problem.

My collection consists of **220 items**.
So the script triggers the maintenance mode of bandcamp.
I think thats the way they are meeting **too many requests** in a small time frame.

So the question is:
How do i download my entire collection or keep track of the already downloaded ones?
I assume that you script isn't closing the successfull ones.

As an afterthought maybe it is possible to tell the script to wait a few minutes before it opens the new tabs?

Regards
KlonAmy

**Comment by klonamy** [comment]
Or do i alter the values as followed:

var rangeStart = 0;
var rangeEnd   = 10; 

var rangeStart = 11;
var rangeEnd   = 21; 

var rangeStart = 22;
var rangeEnd   = 31;

etc...

**Comment by RyanBluth** [comment]
Yeah you can do it that way, 0-10 would download albums 1 to 9, so you would want the next set to start at 10. The script tries to handle maintenance mode by refreshing, so if you see a failure it will retry until it works. Sometimes this takes a while. I find doing 10 albums at a time seems to work pretty well. 
Does that answer your question? There's probably a more elegant way to download a subset, I'm open to suggestions

**Comment by klonamy** [comment]
Thanks. That was exactly the answer i was looking for.
