### ISSUE TITLE
[Enhancement] Ignore duplicate albums

### ISSUE THREAD

**Issue by phrederick** [RyanBluth/Bandcamp-Greasy#6]
Hey mate,
First of all, great script -- very handy.

I wonder if you could slightly improve it by ignoring duplicate albums. This can happen in Bandcamp if you happen to own an album in multiple formats, or different editions (e.g. multiple vinyl colour releases). I briefly looked into removing duplicates from the dloadLinks collection but quickly realised that the links even for the same album are not distinct. I'm sure it can be done, but I am just a novice and it would take me forever.

Thanks!

**Comment by RyanBluth** [comment]
Can you post a screenshot of what this looks like? I only have one version of each album, so it'd help to see what you mean

**Comment by RyanBluth** [comment]
Looks like I can probably just add an option to ignore duplicate titles. Does that sound like it would work?

**Comment by phrederick** [comment]
That sounds like it ought to do the trick. I am happy to test it out for you.

**Comment by RyanBluth** [comment]
Can you give it a try now? I've added a UI as well

**Comment by phrederick** [comment]
Nice! Love the UI update -- I'd almost say that it negates the need for the Range feature now. I realise it's beyond the scope of this enhancement request but it would be cool if you could expose the 'Ignore Duplicates' functionality as a checkbox on the UI too, and maybe have a 'Hide Duplicates' checkbox which pares down the list on the left side of the screen. Just a thought, but this script suits my needs well now.

Thank you!
